chore(core): add check for fork and label for test workflow

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -17,9 +17,6 @@ on:
 jobs:
   test:
     name: Run tests
-    if: |
-      github.event.pull_request.head.repo.full_name == github.repository ||
-      contains(github.event.pull_request.labels.*.name, 'save to test')
     runs-on: ubuntu-latest
     container:
       image: ruby:3.2
@@ -38,6 +35,13 @@ jobs:
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
 
     steps:
+      - name: Check for fork and missing label
+        if: |
+          github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name && !contains(github.event.pull_request.labels.*.name, 'save-to-merge')
+        run: |
+          echo "PR is from a fork and the label 'save-to-merge' is missing, this will not pass ❌"
+          echo "Message for the Maintainer: Please check the tests and if they are ok, add the label 'save-to-merge' to the PR."
+          exit 1
       - name: Setup Javascript (act only)
         # install nodejs only if running locally with act
         # otherwise the actions/setup-node@v4 will fails
@@ -100,8 +104,10 @@ jobs:
           key: yarn-${{ hashFiles('**/yarn.lock') }}
 
       - name: Yarn install
+        # this runs only in PRs from the same repo because of the missing npm token to download the packages
+        if: |
+          github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
         id: test-js
         run: |
-
           yarn install
           yarn test
